name: version-update
description: Github Action for Updating Versions

inputs:
  github_token:
    description: Github Token for git commit or gh pr create
    required: true
  workspaces:
    default: ".:text"
    description: Paths to the workspaces (separated by comma)
  version_message:
    default: version pull request
    description: Version pull request message
  no_pr:
    description: Use pull request to increase the version

outputs:
  version_branch:
    description: Name of the version branch
    value: "${{ steps.version_branch.outputs.version_branch }}"
  pr_title:
    description: Title of the version pull request
    value: "${{ steps.version_branch.outputs.pr_title }}"
  tag:
    description: Tag to have been pushed
    value: "${{ steps.tag_info.outputs.tag }}"
  # status:
  #   dexscription: Status of the version increase
  #   value: "${{ steps. }}"

runs:
  using: "composite"
  steps:
    - name: Git Prerequisites
      id: git_prerequisites
      run: |
        source ${{ github.workspace }}/src/logging.sh
        source ${{ github.workspace }}/src/utils.sh
        source ${{ github.workspace }}/src/git.sh

        git_get_commit_message --store
        git_get_last_created_tag --store
      shell: bash
    - name: Workspace Prerequisites
      id: ws_prerequisites
      run: |
        source ${{ github.workspace }}/src/logging.sh
        source ${{ github.workspace }}/src/utils.sh
        
        source ${{ github.workspace }}/src/package_version_detect.sh
        source ${{ github.workspace }}/src/package_name_detect.sh
        source ${{ github.workspace }}/src/project.sh

        # gather_workspaces_info --workspaces "${{ inputs.workspaces }}" --store
        gather_changed_workspaces_info \
          --workspaces "${{ inputs.workspaces }}" \
          --tag "${{ steps.git_prerequisites.outputs.last_tag }}" \
          --store
      shell: bash

    - name: Increase Version and Commit the Changes
      id: version_increase
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: |
        source ${{ github.workspace }}/src/logging.sh
        source ${{ github.workspace }}/src/utils.sh
        source ${{ github.workspace }}/src/git.sh
        source ${{ github.workspace }}/src/version.sh

        source ${{ github.workspace }}/src/package_version_detect.sh
        source ${{ github.workspace }}/src/package_version_update.sh
        source ${{ github.workspace }}/src/project.sh

        increase_workspaces_versions \
          --workspaces-info "${{ steps.ws_prerequisites.outputs.changed_workspaces_info }}" \
          --commit-message "${{ steps.git_prerequisites.outputs.commit_message }}" \
          --tag "${{ steps.git_prerequisites.outputs.last_tag }}" \
          --store

        git diff

    - name: Set up Git with Authentication
      if: ${{ github.event_name == 'push' && steps.ws_prerequisites.outputs.changed_workspaces_info != steps.version_increase.outputs.updated_workspaces_info }}
      shell: bash
      run: |
        source ${{ github.workspace }}/src/logging.sh
        source ${{ github.workspace }}/src/utils.sh
        source ${{ github.workspace }}/src/git.sh

        git_setup_user
        
        # Configure git with authentication token
        git config --global url."https://x-access-token:${{ inputs.github_token }}@github.com/".insteadOf "https://github.com/"
      env:
        GH_TOKEN: ${{ inputs.github_token }}

    - name: Push new Version
      if: ${{ github.event_name == 'push' && steps.ws_prerequisites.outputs.changed_workspaces_info != steps.version_increase.outputs.updated_workspaces_info }}
      shell: bash
      run: |
        source ${{ github.workspace }}/src/logging.sh
        source ${{ github.workspace }}/src/utils.sh
        source ${{ github.workspace }}/src/git.sh

        source ${{ github.workspace }}/src/package_version_detect.sh
        source ${{ github.workspace }}/src/package_version_update.sh
        source ${{ github.workspace }}/src/project.sh

        updated_version=$(echo "${{ steps.version_increase.outputs.updated_workspaces_info }}" | 
          awk -F';' '{print $1}' | 
          awk -F':' '{ print $NF }')

        if [[ -z "${{ inputs.no_pr }}" ]]; then
          git_create_version_branch \
            --version "${updated_version}" \
            --pr-title "${{ inputs.version_message }} ${updated_version}" \
            --pr-message "pr message"
        else
          git_commit_version_changes \
            --version "${updated_version}" \
            --pr-message "${{ inputs.version_message }} ${updated_version}"
        fi
      env:
        GH_TOKEN: ${{ inputs.github_token }}
