version: "3"

tasks:
  test:bats:install:
    cmds:
      - mkdir -p test
      - git submodule add -b master https://github.com/bats-core/bats-core.git test/bats
      - mkdir -p test/test_helper
      - git submodule add -b master https://github.com/bats-core/bats-support.git test/test_helper/bats-support
      - git submodule add -b master https://github.com/bats-core/bats-assert.git test/test_helper/bats-assert
    desc: Download Bats Dependencies
    generates:
      - test/bats
      - test/test_helper/bats-support
      - test/test_helper/bats-assert
    internal: true
    sources:
      - test/bats/**/*
    summary: |
      Initializes git submodules (tracking the latest commit on the 'master' branch) and downloads project dependencies:
        - bats-core for unit testing (https://github.com/bats-core/bats-core)
        - bats-support for helper functions
        - bats-assert for assertions

  test:bats:update:
    cmds:
      - git submodule update --init --recursive --remote
    desc: Update bats dependencies
    internal: true
    sources:
      - test/**/*.bats
      - test/**/*.sh
    summary: |
      Updates git submodules (tracking the latest commit on the 'master' branch) and downloads project dependencies:
        - bats-core for unit testing (https://github.com/bats-core/bats-core)
        - bats-support for helper functions
        - bats-assert for assertions

  test:
    deps:
      - test:bats:update
    desc: Run Unit Tests
    sources:
      - test/**/*.bats
      - test/**/*.sh
    summary: |
      Executes the test suite using bats.
    cmds:
      - ./test/bats/bin/bats -x ./test/
