name: Test Version Update Action

on:
  push:
    branches:
      - main
      - rewrite

# Add permissions block for proper repository access
permissions:
  contents: write
  pull-requests: write

jobs:
  prereqs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.17.0"
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y jq

          curl -sSL https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

          cargo install cargo-set-version
      - name: Run Tests
        run: |
          task test
      - name: Increase Version
        id: version_step
        uses: ./
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          target_branch: ${{ github.ref }}
          no_pr: true
      - name: Output Results
        run: |
          echo "Version Tag: ${{ steps.version_step.outputs.tag }}"
          echo "Status: ${{ steps.version_step.outputs.status }}"